/**
 * Demo Applicants Fixture (V2 Candidate Profiles)
 * Strict V2 Applicant Contract compliance:
 * - full_name, passport_number, applicant_state (Draft, Registered, CV Generated, Selected, Processing, Stamped, Ticketed, Departed, Cancelled)
 * - medical_status, coc_status, target_job, destination_country, active_placement, etc.
 */

import { V2ApplicantDetails } from "@/lib/api/v2/applicants";

export const DEMO_APPLICANTS: V2ApplicantDetails[] = [
  {
    name: "APP-2026-00101",
    applicant_name: "Fatima Zahra Ahmed",
    full_name: "Fatima Zahra Ahmed",
    first_name: "Fatima",
    middle_name: "Zahra",
    last_name: "Ahmed",
    applicant_state: "Selected",
    active_placement: "PLC-2026-0001",
    passport_number: "EP4892104",
    passport_expiry: "2029-08-14",
    national_id: "ET-NID-992140",
    phone: "+251 91 123 4567",
    gender: "Female",
    date_of_birth: "1997-04-12",
    age: 29,
    marital_status: "Single",
    religion: "Muslim",
    nationality: "Ethiopian",
    destination_country: "Saudi Arabia",
    target_job: "Housemaid",
    applicant_type: "Standard",
    medical_status: "FIT",
    medical_date: "2026-02-10",
    medical_expiry_date: "2026-05-10",
    coc_status: "Passed",
    coc_issue_date: "2026-02-05",
    experience_level: "Experienced",
    experience_years: 3,
    selected_by: "CON-001",
    locked_contractor: "CON-001",
    registration_fee_status: "Paid",
    photo_url: "/placeholder-user.jpg",
    creation: "2026-02-01 10:15:00",
    modified: "2026-02-25 11:20:00",
    income_expense_logs: [
      {
        name: "TXN-001",
        stage: "Registration",
        type: "Income",
        amount: 2500,
        currency: "ETB",
        description: "Standard Candidate Registration Fee",
        date: "2026-02-01",
        status: "Approved",
      },
    ],
  },
  {
    name: "APP-2026-00102",
    applicant_name: "Abebe Bekele Tadesse",
    full_name: "Abebe Bekele Tadesse",
    first_name: "Abebe",
    middle_name: "Bekele",
    last_name: "Tadesse",
    applicant_state: "Processing",
    active_placement: "PLC-2026-0002",
    passport_number: "EP5728190",
    passport_expiry: "2030-01-20",
    national_id: "ET-NID-883921",
    phone: "+251 92 234 5678",
    gender: "Male",
    date_of_birth: "1994-11-03",
    age: 31,
    marital_status: "Married",
    religion: "Orthodox",
    nationality: "Ethiopian",
    destination_country: "Saudi Arabia",
    target_job: "Driver",
    applicant_type: "Standard",
    medical_status: "FIT",
    medical_date: "2026-02-08",
    medical_expiry_date: "2026-05-08",
    coc_status: "Passed",
    coc_issue_date: "2026-02-02",
    experience_level: "Experienced",
    experience_years: 5,
    selected_by: "CON-001",
    locked_contractor: "CON-001",
    registration_fee_status: "Paid",
    photo_url: "/placeholder-user.jpg",
    creation: "2026-01-28 09:00:00",
    modified: "2026-02-24 16:30:00",
    income_expense_logs: [
      {
        name: "TXN-002",
        stage: "Registration",
        type: "Income",
        amount: 2500,
        currency: "ETB",
        description: "Standard Candidate Registration Fee",
        date: "2026-01-28",
        status: "Approved",
      },
      {
        name: "TXN-003",
        stage: "Medical",
        type: "Expense",
        amount: 450,
        currency: "SAR",
        description: "GAMCA Biometric Medical Lab Fee",
        date: "2026-02-08",
        status: "Approved",
      },
    ],
  },
  {
    name: "APP-2026-00103",
    applicant_name: "Meron Hailemariam Mengistu",
    full_name: "Meron Hailemariam Mengistu",
    first_name: "Meron",
    middle_name: "Hailemariam",
    last_name: "Mengistu",
    applicant_state: "Processing",
    active_placement: "PLC-2026-0003",
    passport_number: "EP9182736",
    passport_expiry: "2028-11-15",
    national_id: "ET-NID-772183",
    phone: "+251 93 345 6789",
    gender: "Female",
    date_of_birth: "1999-06-25",
    age: 26,
    marital_status: "Single",
    religion: "Protestant",
    nationality: "Ethiopian",
    destination_country: "Kuwait",
    target_job: "Caregiver",
    applicant_type: "Standard",
    medical_status: "FIT",
    medical_date: "2026-02-12",
    medical_expiry_date: "2026-05-12",
    coc_status: "Passed",
    coc_issue_date: "2026-02-06",
    experience_level: "First Time",
    experience_years: 1,
    selected_by: "CON-002",
    locked_contractor: "CON-002",
    registration_fee_status: "Paid",
    photo_url: "/placeholder-user.jpg",
    creation: "2026-02-03 14:20:00",
    modified: "2026-02-26 15:40:00",
    income_expense_logs: [
      {
        name: "TXN-004",
        stage: "Registration",
        type: "Income",
        amount: 2500,
        currency: "ETB",
        description: "Candidate Registration Fee",
        date: "2026-02-03",
        status: "Approved",
      },
    ],
  },
  {
    name: "APP-2026-00104",
    applicant_name: "Tigist Alemu Worku",
    full_name: "Tigist Alemu Worku",
    first_name: "Tigist",
    middle_name: "Alemu",
    last_name: "Worku",
    applicant_state: "Stamped",
    active_placement: "PLC-2026-0004",
    passport_number: "EP3049182",
    passport_expiry: "2029-05-30",
    national_id: "ET-NID-663819",
    phone: "+251 94 456 7890",
    gender: "Female",
    date_of_birth: "1996-09-18",
    age: 29,
    marital_status: "Single",
    religion: "Muslim",
    nationality: "Ethiopian",
    destination_country: "Saudi Arabia",
    target_job: "Housemaid",
    applicant_type: "Standard",
    medical_status: "FIT",
    medical_date: "2026-01-20",
    medical_expiry_date: "2026-04-20",
    coc_status: "Passed",
    coc_issue_date: "2026-01-15",
    experience_level: "Experienced",
    experience_years: 4,
    selected_by: "CON-001",
    locked_contractor: "CON-001",
    registration_fee_status: "Paid",
    photo_url: "/placeholder-user.jpg",
    creation: "2026-01-12 11:30:00",
    modified: "2026-02-27 17:00:00",
    income_expense_logs: [
      {
        name: "TXN-005",
        stage: "Registration",
        type: "Income",
        amount: 2500,
        currency: "ETB",
        description: "Candidate Registration",
        date: "2026-01-12",
        status: "Approved",
      },
      {
        name: "TXN-006",
        stage: "Embassy",
        type: "Expense",
        amount: 600,
        currency: "SAR",
        description: "Saudi Embassy Visa Endorsement Fee",
        date: "2026-02-20",
        status: "Approved",
      },
    ],
  },
  {
    name: "APP-2026-00105",
    applicant_name: "Dawit Yohannes Gebre",
    full_name: "Dawit Yohannes Gebre",
    first_name: "Dawit",
    middle_name: "Yohannes",
    last_name: "Gebre",
    applicant_state: "Ticketed",
    active_placement: "PLC-2026-0005",
    passport_number: "EP8291047",
    passport_expiry: "2030-03-12",
    national_id: "ET-NID-554920",
    phone: "+251 95 567 8901",
    gender: "Male",
    date_of_birth: "1993-01-15",
    age: 33,
    marital_status: "Married",
    religion: "Orthodox",
    nationality: "Ethiopian",
    destination_country: "Kuwait",
    target_job: "Cook",
    applicant_type: "Standard",
    medical_status: "FIT",
    medical_date: "2026-01-15",
    medical_expiry_date: "2026-04-15",
    coc_status: "Passed",
    coc_issue_date: "2026-01-10",
    experience_level: "Experienced",
    experience_years: 6,
    selected_by: "CON-002",
    locked_contractor: "CON-002",
    registration_fee_status: "Paid",
    photo_url: "/placeholder-user.jpg",
    creation: "2026-01-05 08:45:00",
    modified: "2026-02-28 10:15:00",
    income_expense_logs: [
      {
        name: "TXN-007",
        stage: "Registration",
        type: "Income",
        amount: 2500,
        currency: "ETB",
        description: "Candidate Registration",
        date: "2026-01-05",
        status: "Approved",
      },
      {
        name: "TXN-008",
        stage: "Ticketing",
        type: "Expense",
        amount: 320,
        currency: "USD",
        description: "Ethiopian Airlines Ticket ET-402 Add-KWI",
        date: "2026-02-26",
        status: "Approved",
      },
    ],
  },
  {
    name: "APP-2026-00106",
    applicant_name: "Genet Tesfaye Desta",
    full_name: "Genet Tesfaye Desta",
    first_name: "Genet",
    middle_name: "Tesfaye",
    last_name: "Desta",
    applicant_state: "Departed",
    active_placement: "PLC-2026-0006",
    passport_number: "EP6482019",
    passport_expiry: "2029-10-05",
    national_id: "ET-NID-443819",
    phone: "+251 96 678 9012",
    gender: "Female",
    date_of_birth: "1998-08-30",
    age: 27,
    marital_status: "Single",
    religion: "Muslim",
    nationality: "Ethiopian",
    destination_country: "Saudi Arabia",
    target_job: "Housemaid",
    applicant_type: "Standard",
    medical_status: "FIT",
    medical_date: "2025-12-10",
    medical_expiry_date: "2026-03-10",
    coc_status: "Passed",
    coc_issue_date: "2025-12-05",
    experience_level: "Experienced",
    experience_years: 2,
    selected_by: "CON-001",
    locked_contractor: "CON-001",
    registration_fee_status: "Paid",
    photo_url: "/placeholder-user.jpg",
    creation: "2025-12-01 09:30:00",
    modified: "2026-02-14 08:00:00",
    income_expense_logs: [
      {
        name: "TXN-009",
        stage: "Commission",
        type: "Income",
        amount: 3500,
        currency: "SAR",
        description: "Foreign Agency Placement Commission",
        date: "2026-02-14",
        status: "Approved",
      },
    ],
  },
  {
    name: "APP-2026-00107",
    applicant_name: "Selamawit Kassahun Girma",
    full_name: "Selamawit Kassahun Girma",
    first_name: "Selamawit",
    middle_name: "Kassahun",
    last_name: "Girma",
    applicant_state: "CV Generated",
    passport_number: "EP7719284",
    passport_expiry: "2030-07-22",
    national_id: "ET-NID-332918",
    phone: "+251 97 789 0123",
    gender: "Female",
    date_of_birth: "2000-03-14",
    age: 26,
    marital_status: "Single",
    religion: "Orthodox",
    nationality: "Ethiopian",
    destination_country: "Saudi Arabia",
    target_job: "Housemaid",
    applicant_type: "Standard",
    medical_status: "FIT",
    medical_date: "2026-02-18",
    medical_expiry_date: "2026-05-18",
    coc_status: "Passed",
    coc_issue_date: "2026-02-15",
    experience_level: "First Time",
    experience_years: 0,
    registration_fee_status: "Paid",
    photo_url: "/placeholder-user.jpg",
    creation: "2026-02-15 11:00:00",
    modified: "2026-02-19 14:30:00",
    income_expense_logs: [
      {
        name: "TXN-010",
        stage: "Registration",
        type: "Income",
        amount: 2500,
        currency: "ETB",
        description: "Candidate Registration Fee",
        date: "2026-02-15",
        status: "Approved",
      },
    ],
  },
  {
    name: "APP-2026-00108",
    applicant_name: "Blen Kidane Wolde",
    full_name: "Blen Kidane Wolde",
    first_name: "Blen",
    middle_name: "Kidane",
    last_name: "Wolde",
    applicant_state: "CV Generated",
    passport_number: "EP1829304",
    passport_expiry: "2029-12-10",
    national_id: "ET-NID-221839",
    phone: "+251 98 890 1234",
    gender: "Female",
    date_of_birth: "1998-12-05",
    age: 27,
    marital_status: "Single",
    religion: "Muslim",
    nationality: "Ethiopian",
    destination_country: "Kuwait",
    target_job: "Housemaid",
    applicant_type: "Standard",
    medical_status: "FIT",
    medical_date: "2026-02-20",
    medical_expiry_date: "2026-05-20",
    coc_status: "Passed",
    coc_issue_date: "2026-02-18",
    experience_level: "Experienced",
    experience_years: 2,
    registration_fee_status: "Paid",
    photo_url: "/placeholder-user.jpg",
    creation: "2026-02-18 10:00:00",
    modified: "2026-02-21 16:00:00",
    income_expense_logs: [],
  },
  {
    name: "APP-2026-00109",
    applicant_name: "Hayat Mohammed Nur",
    full_name: "Hayat Mohammed Nur",
    first_name: "Hayat",
    middle_name: "Mohammed",
    last_name: "Nur",
    applicant_state: "Registered",
    passport_number: "EP9928174",
    passport_expiry: "2031-02-14",
    national_id: "ET-NID-110293",
    phone: "+251 99 901 2345",
    gender: "Female",
    date_of_birth: "2001-05-20",
    age: 24,
    marital_status: "Single",
    religion: "Muslim",
    nationality: "Ethiopian",
    destination_country: "Saudi Arabia",
    target_job: "Housemaid",
    applicant_type: "Standard",
    medical_status: "FIT",
    coc_status: "Passed",
    registration_fee_status: "Paid",
    photo_url: "/placeholder-user.jpg",
    creation: "2026-02-27 15:30:00",
    modified: "2026-02-27 15:30:00",
    income_expense_logs: [
      {
        name: "TXN-011",
        stage: "Registration",
        type: "Income",
        amount: 2500,
        currency: "ETB",
        description: "Candidate Registration Fee",
        date: "2026-02-27",
        status: "Approved",
      },
    ],
  },
  {
    name: "APP-2026-00110",
    applicant_name: "Mulugeta Assefa Kebede",
    full_name: "Mulugeta Assefa Kebede",
    first_name: "Mulugeta",
    middle_name: "Assefa",
    last_name: "Kebede",
    applicant_state: "Draft",
    passport_number: "EP4481029",
    passport_expiry: "2030-09-18",
    national_id: "ET-NID-001928",
    phone: "+251 90 012 3456",
    gender: "Male",
    date_of_birth: "1995-07-08",
    age: 30,
    marital_status: "Single",
    religion: "Orthodox",
    nationality: "Ethiopian",
    destination_country: "Saudi Arabia",
    target_job: "Driver",
    applicant_type: "Standard",
    medical_status: "Pending",
    coc_status: "Pending",
    registration_fee_status: "Pending",
    photo_url: "/placeholder-user.jpg",
    creation: "2026-02-28 09:15:00",
    modified: "2026-02-28 09:15:00",
    income_expense_logs: [],
  },
];
