/**
 * Demo Applicants Fixture (V2 Candidate Profiles)
 * Strict V2 Applicant Contract compliance:
 * - full_name, passport_number, applicant_state (Draft, Registered, CV Generated, Selected, Processing, Stamped, Ticketed, Departed, Cancelled)
 * - medical_status, coc_status, target_job, destination_country, active_placement, etc.
 * - Authenticated Standard Saudi Employment Contract Metadata applied across all candidates.
 */

import { V2ApplicantDetails } from "@/lib/api/v2/applicants";

export const DEFAULT_CONTRACT_METADATA = {
  contract_number: "2005450415",
  visa_number: "1908334046",
  sponsor_name: "ABDULLAH AMER MUGHABBIRI ALBARIQI",
  sponsor_id: "1130373143",
  sponsor_phone: "966503221802",
  employer_name: "ABDULLAH AMER MUGHABBIRI ALBARIQI",
  employer_national_id: "1130373143",
  employer_phone: "966503221802",
  destination_city: "Riyadh",
  contractor_name: "Tihamat Asir Recruitment company",
  contractor_license: "3711270",
  contractor_phone: "+966502936544",
  contractor_email: "am25521@hotmail.com",
  monthly_salary: 1000,
  contract_period: 2,
  contract_signed_date: "2026-08-13",
  appointment_date: "2026-08-25",
  contractor_doc: {
    file_name: "ERAHMET YESUF ABRIE CONT.pdf",
    file_attachment: "/contract_sample.pdf",
    attached_file: "/contract_sample.pdf",
    contract_number: "2005450415",
    visa_number: "1908334046",
    sponsor_name: "ABDULLAH AMER MUGHABBIRI ALBARIQI",
    sponsor_id: "1130373143",
    sponsor_phone: "966503221802",
    destination_city: "Riyadh",
    destination_country: "Saudi Arabia",
    contractor_name: "Tihamat Asir Recruitment company",
    contractor_license: "3711270",
    contractor_phone: "+966502936544",
    contractor_email: "am25521@hotmail.com",
    salary: 1000,
    contract_period: 2,
    contract_signed_date: "2026-08-13",
    status: "Approved",
    uploaded_at: "2026-08-13",
  },
};

export const DEMO_APPLICANTS: V2ApplicantDetails[] = [
  {
    name: "APP-2026-00101",
    applicant_name: "Fatima Zahra Ahmed",
    full_name: "Fatima Zahra Ahmed",
    first_name: "Fatima",
    middle_name: "Zahra",
    last_name: "Ahmed",
    applicant_state: "Selected",
    active_placement: "PLC-2026-0001",
    passport_number: "EP4892104",
    passport_expiry: "2029-08-14",
    national_id: "ET-NID-992140",
    phone: "+251 91 123 4567",
    gender: "Female",
    date_of_birth: "1997-04-12",
    age: 29,
    marital_status: "Single",
    religion: "Muslim",
    nationality: "Ethiopian",
    destination_country: "Saudi Arabia",
    target_job: "Housemaid",
    applicant_type: "Standard",
    medical_status: "FIT",
    medical_date: "2026-02-10",
    medical_expiry_date: "2026-05-10",
    coc_status: "Passed",
    coc_issue_date: "2026-02-05",
    experience_level: "Experienced",
    experience_years: 3,
    selected_by: "CON-001",
    locked_contractor: "CON-001",
    registration_fee_status: "Paid",
    photo_url: "/placeholder-user.jpg",
    creation: "2026-02-01 10:15:00",
    modified: "2026-02-25 11:20:00",
    ...DEFAULT_CONTRACT_METADATA,
    income_expense_logs: [
      {
        name: "TXN-001",
        stage: "Registration",
        type: "Income",
        amount: 2500,
        currency: "ETB",
        description: "Standard Candidate Registration Fee",
        date: "2026-02-01",
        status: "Approved",
      },
    ],
  },
  {
    name: "APP-2026-00102",
    applicant_name: "Abebe Bekele Tadesse",
    full_name: "Abebe Bekele Tadesse",
    first_name: "Abebe",
    middle_name: "Bekele",
    last_name: "Tadesse",
    applicant_state: "Processing",
    active_placement: "PLC-2026-0002",
    passport_number: "EP5728190",
    passport_expiry: "2030-01-20",
    national_id: "ET-NID-883921",
    phone: "+251 92 234 5678",
    gender: "Male",
    date_of_birth: "1994-11-03",
    age: 31,
    marital_status: "Married",
    religion: "Orthodox",
    nationality: "Ethiopian",
    destination_country: "Saudi Arabia",
    target_job: "Driver",
    applicant_type: "Standard",
    medical_status: "FIT",
    medical_date: "2026-02-08",
    medical_expiry_date: "2026-05-08",
    coc_status: "Passed",
    coc_issue_date: "2026-02-02",
    experience_level: "Experienced",
    experience_years: 5,
    selected_by: "CON-001",
    locked_contractor: "CON-001",
    registration_fee_status: "Paid",
    photo_url: "/placeholder-user.jpg",
    creation: "2026-01-28 09:00:00",
    modified: "2026-02-24 16:30:00",
    ...DEFAULT_CONTRACT_METADATA,
    income_expense_logs: [
      {
        name: "TXN-002",
        stage: "Registration",
        type: "Income",
        amount: 2500,
        currency: "ETB",
        description: "Standard Candidate Registration Fee",
        date: "2026-01-28",
        status: "Approved",
      },
      {
        name: "TXN-003",
        stage: "Medical",
        type: "Expense",
        amount: 450,
        currency: "SAR",
        description: "GAMCA Biometric Medical Lab Fee",
        date: "2026-02-08",
        status: "Approved",
      },
    ],
  },
  {
    name: "APP-2026-00103",
    applicant_name: "Meron Hailemariam Mengistu",
    full_name: "Meron Hailemariam Mengistu",
    first_name: "Meron",
    middle_name: "Hailemariam",
    last_name: "Mengistu",
    applicant_state: "Processing",
    active_placement: "PLC-2026-0003",
    passport_number: "EP9182736",
    passport_expiry: "2028-11-15",
    national_id: "ET-NID-772183",
    phone: "+251 93 345 6789",
    gender: "Female",
    date_of_birth: "1999-06-25",
    age: 26,
    marital_status: "Single",
    religion: "Protestant",
    nationality: "Ethiopian",
    destination_country: "Kuwait",
    target_job: "Caregiver",
    applicant_type: "Standard",
    medical_status: "FIT",
    medical_date: "2026-02-12",
    medical_expiry_date: "2026-05-12",
    coc_status: "Passed",
    coc_issue_date: "2026-02-06",
    experience_level: "First Time",
    experience_years: 0,
    selected_by: "CON-002",
    locked_contractor: "CON-002",
    registration_fee_status: "Paid",
    photo_url: "/placeholder-user.jpg",
    creation: "2026-02-05 11:15:00",
    modified: "2026-02-26 15:40:00",
    contract_number: "2005450415",
    visa_number: "1908334046",
    sponsor_name: "ABDULLAH AMER MUGHABBIRI ALBARIQI",
    sponsor_id: "1130373143",
    sponsor_phone: "966503221802",
    destination_city: "Kuwait City",
    contractor_name: "Gulf Horizon Recruitment Bureau",
    monthly_salary: 120,
    contract_period: 2,
    contract_signed_date: "2026-08-13",
    appointment_date: "2026-08-25",
    contractor_doc: {
      ...DEFAULT_CONTRACT_METADATA.contractor_doc,
      destination_country: "Kuwait",
      destination_city: "Kuwait City",
      contractor_name: "Gulf Horizon Recruitment Bureau",
      salary: 120,
    },
    income_expense_logs: [
      {
        name: "TXN-004",
        stage: "Registration",
        type: "Income",
        amount: 2500,
        currency: "ETB",
        description: "Standard Candidate Registration Fee",
        date: "2026-02-05",
        status: "Approved",
      },
    ],
  },
  {
    name: "APP-2026-00104",
    applicant_name: "Tigist Alemu Worku",
    full_name: "Tigist Alemu Worku",
    first_name: "Tigist",
    middle_name: "Alemu",
    last_name: "Worku",
    applicant_state: "Stamped",
    active_placement: "PLC-2026-0004",
    passport_number: "EP3049182",
    passport_expiry: "2029-05-18",
    national_id: "ET-NID-663821",
    phone: "+251 94 456 7890",
    gender: "Female",
    date_of_birth: "1996-08-19",
    age: 30,
    marital_status: "Divorced",
    religion: "Muslim",
    nationality: "Ethiopian",
    destination_country: "Saudi Arabia",
    target_job: "Housemaid",
    applicant_type: "Standard",
    medical_status: "FIT",
    medical_date: "2026-01-20",
    medical_expiry_date: "2026-04-20",
    coc_status: "Passed",
    coc_issue_date: "2026-01-15",
    experience_level: "Experienced",
    experience_years: 4,
    experience_country: "Saudi Arabia",
    experience_period: "4 Years",
    selected_by: "CON-001",
    locked_contractor: "CON-001",
    registration_fee_status: "Paid",
    photo_url: "/placeholder-user.jpg",
    creation: "2026-01-15 14:00:00",
    modified: "2026-02-27 17:00:00",
    ...DEFAULT_CONTRACT_METADATA,
    income_expense_logs: [
      {
        name: "TXN-005",
        stage: "Registration",
        type: "Income",
        amount: 2500,
        currency: "ETB",
        description: "Standard Candidate Registration Fee",
        date: "2026-01-15",
        status: "Approved",
      },
      {
        name: "TXN-006",
        stage: "Embassy",
        type: "Expense",
        amount: 350,
        currency: "SAR",
        description: "Saudi Embassy Visa Stamping Fee",
        date: "2026-02-20",
        status: "Approved",
      },
    ],
  },
  {
    name: "APP-2026-00105",
    applicant_name: "Dawit Yohannes Gebre",
    full_name: "Dawit Yohannes Gebre",
    first_name: "Dawit",
    middle_name: "Yohannes",
    last_name: "Gebre",
    applicant_state: "Ticketed",
    active_placement: "PLC-2026-0005",
    passport_number: "EP8291047",
    passport_expiry: "2031-03-10",
    national_id: "ET-NID-554912",
    phone: "+251 95 567 8901",
    gender: "Male",
    date_of_birth: "1993-02-14",
    age: 33,
    marital_status: "Married",
    religion: "Orthodox",
    nationality: "Ethiopian",
    destination_country: "Kuwait",
    target_job: "Electrician",
    applicant_type: "Standard",
    medical_status: "FIT",
    medical_date: "2026-01-10",
    medical_expiry_date: "2026-04-10",
    coc_status: "Passed",
    coc_issue_date: "2026-01-05",
    experience_level: "Experienced",
    experience_years: 6,
    selected_by: "CON-002",
    locked_contractor: "CON-002",
    registration_fee_status: "Paid",
    photo_url: "/placeholder-user.jpg",
    creation: "2026-01-08 08:30:00",
    modified: "2026-02-28 10:45:00",
    contract_number: "2005450415",
    visa_number: "1908334046",
    sponsor_name: "ABDULLAH AMER MUGHABBIRI ALBARIQI",
    sponsor_id: "1130373143",
    sponsor_phone: "966503221802",
    destination_city: "Kuwait City",
    contractor_name: "Gulf Horizon Recruitment Bureau",
    monthly_salary: 150,
    contract_period: 2,
    contract_signed_date: "2026-08-13",
    appointment_date: "2026-08-25",
    contractor_doc: {
      ...DEFAULT_CONTRACT_METADATA.contractor_doc,
      destination_country: "Kuwait",
      destination_city: "Kuwait City",
      contractor_name: "Gulf Horizon Recruitment Bureau",
      salary: 150,
    },
    income_expense_logs: [
      {
        name: "TXN-007",
        stage: "Registration",
        type: "Income",
        amount: 2500,
        currency: "ETB",
        description: "Standard Candidate Registration Fee",
        date: "2026-01-08",
        status: "Approved",
      },
      {
        name: "TXN-008",
        stage: "Ticketing",
        type: "Expense",
        amount: 18500,
        currency: "ETB",
        description: "Kuwait Airways One-Way Flight Ticket",
        date: "2026-02-26",
        status: "Approved",
      },
    ],
  },
  {
    name: "APP-2026-00106",
    applicant_name: "Genet Tesfaye Desta",
    full_name: "Genet Tesfaye Desta",
    first_name: "Genet",
    middle_name: "Tesfaye",
    last_name: "Desta",
    applicant_state: "Departed",
    active_placement: "PLC-2026-0006",
    passport_number: "EP1928374",
    passport_expiry: "2029-12-05",
    national_id: "ET-NID-443829",
    phone: "+251 96 678 9012",
    gender: "Female",
    date_of_birth: "1998-10-30",
    age: 27,
    marital_status: "Single",
    religion: "Muslim",
    nationality: "Ethiopian",
    destination_country: "Saudi Arabia",
    target_job: "Housemaid",
    applicant_type: "Standard",
    medical_status: "FIT",
    medical_date: "2025-12-15",
    medical_expiry_date: "2026-03-15",
    coc_status: "Passed",
    coc_issue_date: "2025-12-10",
    experience_level: "Experienced",
    experience_years: 2,
    selected_by: "CON-001",
    locked_contractor: "CON-001",
    registration_fee_status: "Paid",
    photo_url: "/placeholder-user.jpg",
    departure_date: "2026-02-14",
    creation: "2025-12-01 11:00:00",
    modified: "2026-02-15 09:00:00",
    ...DEFAULT_CONTRACT_METADATA,
    income_expense_logs: [
      {
        name: "TXN-009",
        stage: "Registration",
        type: "Income",
        amount: 2500,
        currency: "ETB",
        description: "Standard Candidate Registration Fee",
        date: "2025-12-01",
        status: "Approved",
      },
      {
        name: "TXN-010",
        stage: "Departure",
        type: "Income",
        amount: 3500,
        currency: "SAR",
        description: "Agency Placement Commission Accrual",
        date: "2026-02-14",
        status: "Approved",
      },
    ],
  },
  {
    name: "APP-2026-00107",
    applicant_name: "Almaz Kebede Haile",
    full_name: "Almaz Kebede Haile",
    first_name: "Almaz",
    middle_name: "Kebede",
    last_name: "Haile",
    applicant_state: "Draft",
    passport_number: "EP7719284",
    passport_expiry: "2030-07-22",
    national_id: "ET-NID-332918",
    phone: "+251 97 789 0123",
    gender: "Female",
    date_of_birth: "2000-04-18",
    age: 26,
    marital_status: "Single",
    religion: "Orthodox",
    nationality: "Ethiopian",
    destination_country: "Saudi Arabia",
    target_job: "Housemaid",
    applicant_type: "Standard",
    medical_status: "Pending",
    coc_status: "Pending",
    experience_level: "First Time",
    experience_years: 0,
    registration_fee_status: "Unpaid",
    photo_url: "/placeholder-user.jpg",
    creation: "2026-02-20 09:00:00",
    modified: "2026-02-20 09:00:00",
    ...DEFAULT_CONTRACT_METADATA,
    income_expense_logs: [],
  },
  {
    name: "APP-2026-00108",
    applicant_name: "Kalkidan Getachew Tura",
    full_name: "Kalkidan Getachew Tura",
    first_name: "Kalkidan",
    middle_name: "Getachew",
    last_name: "Tura",
    applicant_state: "Registered",
    passport_number: "EP6628193",
    passport_expiry: "2029-09-30",
    national_id: "ET-NID-221948",
    phone: "+251 98 890 1234",
    gender: "Female",
    date_of_birth: "1999-12-08",
    age: 26,
    marital_status: "Single",
    religion: "Protestant",
    nationality: "Ethiopian",
    destination_country: "Saudi Arabia",
    target_job: "Housemaid",
    applicant_type: "Standard",
    medical_status: "FIT",
    medical_date: "2026-02-18",
    medical_expiry_date: "2026-05-18",
    coc_status: "Passed",
    coc_issue_date: "2026-02-15",
    experience_level: "First Time",
    experience_years: 0,
    registration_fee_status: "Paid",
    photo_url: "/placeholder-user.jpg",
    creation: "2026-02-15 13:30:00",
    modified: "2026-02-22 15:00:00",
    ...DEFAULT_CONTRACT_METADATA,
    income_expense_logs: [
      {
        name: "TXN-011",
        stage: "Registration",
        type: "Income",
        amount: 2500,
        currency: "ETB",
        description: "Standard Candidate Registration Fee",
        date: "2026-02-15",
        status: "Approved",
      },
    ],
  },
  {
    name: "APP-2026-00109",
    applicant_name: "Saba Wondimu Kassa",
    full_name: "Saba Wondimu Kassa",
    first_name: "Saba",
    middle_name: "Wondimu",
    last_name: "Kassa",
    applicant_state: "CV Generated",
    passport_number: "EP5519283",
    passport_expiry: "2028-06-14",
    national_id: "ET-NID-110938",
    phone: "+251 99 901 2345",
    gender: "Female",
    date_of_birth: "1997-08-22",
    age: 28,
    marital_status: "Single",
    religion: "Muslim",
    nationality: "Ethiopian",
    destination_country: "Saudi Arabia",
    target_job: "Housemaid",
    applicant_type: "Standard",
    medical_status: "FIT",
    medical_date: "2026-02-12",
    medical_expiry_date: "2026-05-12",
    coc_status: "Passed",
    coc_issue_date: "2026-02-10",
    experience_level: "Experienced",
    experience_years: 2,
    registration_fee_status: "Paid",
    cv_file_url: "/demo/cv_preview.pdf",
    photo_url: "/placeholder-user.jpg",
    creation: "2026-02-10 10:00:00",
    modified: "2026-02-25 12:00:00",
    ...DEFAULT_CONTRACT_METADATA,
    income_expense_logs: [
      {
        name: "TXN-012",
        stage: "Registration",
        type: "Income",
        amount: 2500,
        currency: "ETB",
        description: "Standard Candidate Registration Fee",
        date: "2026-02-10",
        status: "Approved",
      },
    ],
  },
  {
    name: "APP-2026-00110",
    applicant_name: "Asnekech Tedesse Wachamo",
    full_name: "Asnekech Tedesse Wachamo",
    first_name: "Asnekech",
    middle_name: "Tedesse",
    last_name: "Wachamo",
    applicant_state: "CV Generated",
    passport_number: "EQ2576096",
    passport_expiry: "2030-05-12",
    passport_issue_date: "2025-05-13",
    place_of_issue: "Addis Ababa",
    place_of_birth: "Angecha",
    leaving_town: "Addis Ababa",
    national_id: "ET-NID-992014",
    phone: "+251 91 234 5678",
    gender: "Female",
    date_of_birth: "2000-12-02",
    age: 25,
    marital_status: "Single",
    religion: "Non-Muslim",
    nationality: "Ethiopian",
    destination_country: "Saudi Arabia",
    target_job: "Housemaid",
    applicant_type: "Standard",
    medical_status: "FIT",
    medical_date: "2026-02-15",
    medical_expiry_date: "2026-05-15",
    coc_status: "Passed",
    coc_issue_date: "2026-02-12",
    experience_level: "First Time",
    experience_years: 0,
    height: 160,
    weight: 55,
    complexion: "Fair",
    education_level: "Primary School",
    english_level: "Fair",
    arabic_level: "Fair",
    skill_cleaning: 1,
    skill_washing: 1,
    skill_ironing: 1,
    skill_baby_sitting: 1,
    skill_children_care: 1,
    registration_fee_status: "Paid",
    photo_url: "/placeholder-user.jpg",
    creation: "2026-02-12 09:30:00",
    modified: "2026-02-28 14:00:00",
    ...DEFAULT_CONTRACT_METADATA,
    income_expense_logs: [
      {
        name: "TXN-013",
        stage: "Registration",
        type: "Income",
        amount: 2500,
        currency: "ETB",
        description: "Standard Candidate Registration Fee",
        date: "2026-02-12",
        status: "Approved",
      },
    ],
  },
];
