/**
 * Demo Contractors Fixture (V2 Foreign Agencies)
 * Follows V2 Contractor contract: name, contractor_name, country, user_email, user_first_name, contact_person, phone, email, active_status
 */

import { V2ContractorRecord } from "@/lib/api/v2/contractors";

export const DEMO_CONTRACTORS: V2ContractorRecord[] = [
  {
    name: "CON-001",
    contractor_name: "Al-Riyadh International Manpower",
    company_name: "Al-Riyadh International Manpower",
    country: "Saudi Arabia",
    user_email: "recruitment@alriyadh-manpower.sa",
    user_first_name: "Tariq Al-Mansoor",
    contact_person: "Tariq Al-Mansoor",
    phone: "+966 50 123 4567",
    whatsapp: "+966 50 123 4567",
    email: "recruitment@alriyadh-manpower.sa",
    active_status: 1,
    communication_manager: "Sara Ahmed",
    notes: "Primary Tier-1 partner in Riyadh. Specializes in domestic and hospitality workforce.",
    creation: "2026-01-10 09:30:00",
    modified: "2026-02-15 14:20:00",
  },
  {
    name: "CON-002",
    contractor_name: "Gulf Horizon Recruitment Bureau",
    company_name: "Gulf Horizon Recruitment Bureau",
    country: "Kuwait",
    user_email: "operations@gulfhorizon-kw.com",
    user_first_name: "Bader Al-Sabah",
    contact_person: "Bader Al-Sabah",
    phone: "+965 99 887 766",
    whatsapp: "+965 99 887 766",
    email: "operations@gulfhorizon-kw.com",
    active_status: 1,
    communication_manager: "Sara Ahmed",
    notes: "Exclusive Kuwait labor contract partner. Handles Ministry of Social Affairs clearances.",
    creation: "2026-01-14 11:00:00",
    modified: "2026-02-18 16:45:00",
  },
  {
    name: "CON-003",
    contractor_name: "Al-Ahly Recruitment Group KSA",
    company_name: "Al-Ahly Recruitment Group KSA",
    country: "Saudi Arabia",
    user_email: "contact@alahly-recruitment.sa",
    user_first_name: "Fahad Al-Harbi",
    contact_person: "Fahad Al-Harbi",
    phone: "+966 55 432 1098",
    whatsapp: "+966 55 432 1098",
    email: "contact@alahly-recruitment.sa",
    active_status: 1,
    communication_manager: "Sara Ahmed",
    notes: "Dammam and Eastern Province labor quota sponsor.",
    creation: "2026-01-20 08:15:00",
    modified: "2026-02-20 10:10:00",
  },
  {
    name: "CON-004",
    contractor_name: "Jeddah Domestic Services Agency",
    company_name: "Jeddah Domestic Services Agency",
    country: "Saudi Arabia",
    user_email: "info@jeddahservices.sa",
    user_first_name: "Khalid Al-Zahrani",
    contact_person: "Khalid Al-Zahrani",
    phone: "+966 54 987 6543",
    whatsapp: "+966 54 987 6543",
    email: "info@jeddahservices.sa",
    active_status: 1,
    communication_manager: "Sara Ahmed",
    notes: "Western Region specialized domestic care placements.",
    creation: "2026-02-01 13:40:00",
    modified: "2026-02-25 11:30:00",
  },
];
